# Generated by Django 4.1 on 2022-11-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_usermusic_userfilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='hassurvey',
            field=models.IntegerField(default=0),
        ),
    ]
