# Generated by Django 4.1 on 2022-11-20 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_userprofileinfo_hassurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userurl',
            name='timestamp',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='UserFilm',
        ),
    ]
