# Generated by Django 4.1 on 2022-11-25 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_userurl_timestamp_delete_userfilm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='image',
            field=models.ImageField(default='server/users/defaultuser.gif', null=True, upload_to='server/users/'),
        ),
        migrations.AlterField(
            model_name='userurl',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
