# Generated by Django 4.1 on 2022-11-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_userprofileinfo_image_alter_userurl_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userurl',
            name='frequency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userurl',
            name='robustness',
            field=models.FloatField(default=0),
        ),
    ]
