# Generated by Django 4.1 on 2022-12-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='content',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
        migrations.AddField(
            model_name='feedback',
            name='exp',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='suggestion',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
