# Generated by Django 4.1 on 2023-04-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_remove_feedback_content_remove_feedback_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='image',
            field=models.ImageField(default='server/static/server/users/defaultuser.gif', null=True, upload_to='server/static/server/users/'),
        ),
    ]
