# Generated by Django 4.1 on 2023-05-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_userprofileinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='image',
        ),
    ]
