# Generated by Django 4.1 on 2023-06-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_alter_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
