# Generated by Django 4.0.4 on 2024-04-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_token_chat_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='code',
            new_name='b_token',
        ),
        migrations.AddField(
            model_name='token',
            name='lat_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
