# Generated by Django 4.0.4 on 2024-04-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_rename_code_token_b_token_token_lat_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='cf_bm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='cf_clearance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
